a14n/urls.py
from django.urls import include, path

from a14n import views as a14n_views

urlpatterns = [
    path('signup/', a14n_views.signup, name='signup'),
    path('', include('django.contrib.auth.urls')),
]

lead/urls.py
from django.urls import include, path

from lead.views import ContactCreate, ContactDelete, ContactDetail, ContactList, ContactUpdate

app_name = 'lead'
urlpatterns = [
    path('', ContactList.as_view(), name='index'),
    path('add/', ContactCreate.as_view(), name='add'),
    path('<int:contact_id>', ContactDetail.as_view(), name='view'),
    path('<int:contact_id>/edit/', ContactUpdate.as_view(), name='edit'),
    path('<int:contact_id>/delete/', ContactDelete.as_view(), name='delete'),
]

lead/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

class Contact(models.Model):
    """
    Class implementing a contact
    Based on django.contrib.auth.models.AbstractUser
    Address, phone, URL & organization will move in dedicated table in future
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), blank=True)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    date_edit = models.DateTimeField(_('last edit'), auto_now=True, blank=True, null=True)
    date_birthday = models.DateField(_('birth_date'), auto_now=False, auto_now_add=False, blank=True, null=True)
    address_label = models.CharField(_('address label'), max_length=50, blank=True)
    address_line_1 = models.CharField(_('address line 1'), max_length=50, blank=True)
    address_line_2 = models.CharField(_('address line 2'), max_length=50, blank=True)
    address_zip = models.CharField(_('zipcode'), max_length=50, blank=True)
    address_city = models.CharField(_('city'), max_length=50, blank=True)
    address_country = models.CharField(_('country'), max_length=50, blank=True)
    phone = models.CharField(_('phone'), max_length=50, blank=True)
    title = models.CharField(_('title'), max_length=50, blank=True)
    role = models.CharField(_('role'), max_length=50, blank=True)
    organization = models.CharField(_('organization'), max_length=50, blank=True)
    url = models.CharField(_('url') , max_length=50, blank=True)
    note = models.TextField(_('note'), blank=True)


    def __str__(self):
        """ Return shortname """
        return self.get_short_name()


    def all(self):
        """ return a dict containing all attributes """
        return {
            attr: val
            for (attr, val) in vars(self).items()
            if not attr.startswith('_')
        }


    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()


    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name


    def was_created_today(self):
        """ Return last contact created """
        return self.date_joined <= timezone.now() + datetime.timedelta(days=1)

    # TODO : this method schould avoid setting`success_url` in `lead.views`
    # TODO : see https://docs.djangoproject.com/fr/2.1/ref/models/instances/#django.db.models.Model.get_absolute_url
    # TODO : see https://docs.djangoproject.com/fr/2.1/topics/class-based-views/generic-editing/#model-forms
    # def get_absolute_url(self):
        # return reverse('contact:view', kwargs={'contact_id': self.contact_id})

lead/forms.py
from django.forms import ModelForm

from lead.models import Contact

class ContactForm(ModelForm):

    class Meta:
        model = Contact
        exclude = ['user','date_joined']
        localized_fields = '__all__'

lead/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import DetailView, ListView

from lead.forms import ContactForm
from lead.models import Contact


class ContactList(LoginRequiredMixin, ListView):
    """
    Index page of `lead` app, show contact list of the authenticated user
    """
    context_object_name = 'contact_list'

    def get_queryset(self):
        return Contact.objects.filter(user=self.request.user)


class ContactDetail(LoginRequiredMixin, DetailView):
    """
    Show details of the choosen contact
    """
    pk_url_kwarg = 'contact_id'

    def get_queryset(self):
        return Contact.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contact_fields'] = Contact.objects.all()

        return context


class ContactCreate(LoginRequiredMixin, CreateView):
    """
    Create a new Contact
    """
    model = Contact
    form_class = ContactForm
    success_url = reverse_lazy('lead:index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ContactUpdate(LoginRequiredMixin, UpdateView):
    """
    Update a contact
    """
    form_class = ContactForm
    pk_url_kwarg = 'contact_id'
    # success_url = reverse_lazy('lead:view', kwargs={'contact_id': pk_url_kwarg})
    success_url = reverse_lazy('lead:index')

    def get_queryset(self):
        return Contact.objects.filter(user=self.request.user)


class ContactDelete(LoginRequiredMixin, DeleteView):
    """
    Delete a contact
    """
    pk_url_kwarg = 'contact_id'
    success_url = reverse_lazy('lead:index')

    def get_queryset(self):
        return Contact.objects.filter(user=self.request.user)

lead/templates/lead/add.html
{% extends "lead/contact_list.html" %}

{% block maincontent %}
  <p>Ajouter un contact</p>
  {{ form }}
{% endblock maincontent %}

lead/templates/lead/contact_confirm_delete.html
{% extends "lead/contact_list.html" %}

{% block maincontent %}
  <div class="alert--warning">
    Suppression du contact : <strong>{{contact.get_full_name|title}}</strong> ?
  </div>

  <div class="grid-4-small-1 has-gutter pam">

    <div class="grid-offset"></div>

    <div>
      <form method="post" action="">{% csrf_token %}
        <input type="Submit" name="submit" value="Confirmer" class="btn--danger" title="Supprimer {{contact.get_full_name|title}}"/>
      </form>
    </div>

    <div>
      <a href="{% url 'lead:view' contact.id %}" title="Retour à la page du contact {{contact.get_full_name|title}}">
        <button class="btn--success" >Annuler</button>
      </a>
    </div>

  </div>
{% endblock maincontent %}

<!--
<button class="btn" >Confirmer</button>
<a href="{% url 'lead:delete' contact.id %}" ></a>
-->

lead/templates/lead/contact_detail.html
{% extends "lead/contact_list.html" %}

{% block maincontent %}
  <p>Fiche contact : <strong>{{contact.get_full_name|title}}</strong></p>
  <div class="grid-2-small-1 has-gutter">
    <div class="txtcenter"><strong>{{contact.was_created_today|yesno:"Nouveau contact,Ancien contact"}}</strong></div>
  {% for label, field in contact.all.items %}
    <div class="txtcenter"><strong>{{label}}</strong> : <em>{{field}}</em></div>
  {% endfor %}
  </div>
  <div class="flex-container pam">
    <div class="item-center">
      <a href="{% url 'lead:delete' contact.id %}" title="Supprimer le contact «{{contact.get_full_name|title}}»">
        <button class="btn--danger" >
          Supprimer le contact <strong>{{contact.get_full_name|title}}</strong>
        </button>
      </a>
    </div>
  </div>
{% endblock maincontent %}

lead/templates/lead/contact_form.html
{% extends "lead/contact_list.html" %}

{% block maincontent %}
  <p>{{ contact_id }}</p>

<form method="post" action="" class="">
{% csrf_token %}
  <table>
  {{ form.as_table }}
  </table>
  <input type="Submit" name="submit" id="" value="Envoyer" />
<form>

{% endblock maincontent %}

lead/templates/lead/contact_list.html
{% extends "base.html" %}

{% block title %}Mes contacts{% endblock %}

{% block headercontent %}
    <h2>Mes contacts</h2>
{% endblock headercontent %}

{% block navcontent %}
  <ul class="pam">
    <li class="pam inbl"><a href="{% url 'lead:index' %}" title="btn--small">Mes contacts</a></li>
    <li class="pam inbl"><a href="{% url 'lead:add' %}" title="btn--small">Ajouter un contact</a></li>
  </ul>
{% endblock navcontent %}

{% block maincontent %}

  {% if contact_list %}
      {% include 'lead/list.html' %}

  {% else %}
    {% include "lead/none.html" %}

  {% endif %}

{% endblock maincontent %}

lead/templates/lead/index.html
{% extends "base.html" %}

{% block title %}Mes contacts{% endblock %}

{% block headercontent %}
    <h2>Mes contacts</h2>
{% endblock headercontent %}

{% block navcontent %}
  <ul class="pam">
    <li class="pam inbl"><a href="{% url 'lead:index' %}" title="btn--small">Mes contacts</a></li>
    <li class="pam inbl"><a href="{% url 'lead:add' %}" title="btn--small">Ajouter un contact</a></li>
  </ul>
{% endblock navcontent %}

{% block maincontent %}

  {% if status %}
    {% include "lead/list.html" %}

  {% else %}
    {% include "lead/none.html" %}

  {% endif %}

{% endblock maincontent %}

lead/templates/lead/list.html
{% for contact in contact_list %}
    <div class="flex-container">
      <div class="item-center">
        <a href="{% url 'lead:view' contact.id %}" title="Voir la fiche de {{ contact|title }}">
          <strong>{{ contact.get_full_name|title }}</strong>
        </a>
        [<em>
            <a href="{% url 'lead:edit' contact.id %}" title="Éditer la fiche de {{ contact|title }}">Modifier</a> -
            <a href="{% url 'lead:delete' contact.id %}" title="Supprimer la fiche de {{ contact|title }}">Supprimer</a>
        </em>]
      </div>
    </div>
{% endfor %}

lead/templates/lead/none.html
  <p>Oups… rien n'à été trouvé!</p>

lead/templates/lead/table.html
  <table class="table table--zebra">
    <tr>
  {% for label in label_list %}
      <th>{{ label }}</th>
  {% endfor %}
      <th></th>
      <th></th>
    </tr>

  {% for line in contacts %}
    <tr>
    {% for key, value in line.items %}
      <td>{{ value }}</td>
    {% endfor %}
      <td><a href="{% url 'lead:view' line.id %}" title="Voir la fiche" class="btn--primary" role="button">Voir</a></td>
      <td><a href="{% url 'lead:edit' line.id %}" title="Éditer la fiche" class="btn--primary" role="button">Modifier</a></td>
    </tr>
  {% endfor %}

  </table>