a14n/urls.py
from django.urls import include, path

from a14n import views as a14n_views

urlpatterns = [
    path('signup/', a14n_views.signup, name='signup'),
    path('', include('django.contrib.auth.urls')),
]

lead/urls.py
from django.urls import include, path

from lead.views import ContactCreate, ContactDelete, ContactDetail, ContactList, ContactUpdate

app_name = 'lead'
urlpatterns = [
    path('', ContactList.as_view(), name='index'),
    path('add/', ContactCreate.as_view(), name='add'),
    path('<int:contact_id>', ContactDetail.as_view(), name='view'),
    path('<int:contact_id>/edit/', ContactUpdate.as_view(), name='edit'),
    path('<int:contact_id>/delete/', ContactDelete.as_view(), name='delete'),
]

user/urls.py
from user.views import UserDetail, UserUpdate

from django.urls import path


app_name = 'user'
urlpatterns = [
    path('', UserDetail.as_view(), name='detail'),
    path('edit', UserUpdate.as_view(), name='update'),
]

user/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User


class UserForm(ModelForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name']

user/views.py
from user.forms import UserForm

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView
from django.views.generic import DetailView

from lead.models import Contact

class UserDetail(LoginRequiredMixin, DetailView):
    """
    Show details of the connected user
    """

    def get_object(self):
        return get_object_or_404(User, pk=self.request.user.id)

    def get_context_data(self, **kwargs):
        user = User.objects.filter(
            username=self.request.user
        ).values('date_joined', 'last_login')

        try:
            last_contact = Contact.objects.filter(
                user=self.request.user
            ).values(
            ).order_by(
                '-date_joined',
            )[:1].get()

        except ObjectDoesNotExist:
            last_contact = ''

        context = super().get_context_data(**kwargs)
        context.update({
            'last_contact': last_contact,
            'date_joined': user.values_list('date_joined', flat=True).get(),
            'last_login': user.values_list('last_login', flat=True).get(),
        })

        return context


class UserUpdate(LoginRequiredMixin, UpdateView):
    """
    Update user informations
    """
    form_class = UserForm
    success_url = reverse_lazy('user:detail')

    def get_object(self):
        return get_object_or_404(User, pk=self.request.user.id)

user/templates/user/index.html
{% extends 'base.html' %}

{% block title %}Mon compte{% endblock %}

{% block headercontent %}
    <h2>Mon compte</h2>
{% endblock headercontent %}

{% block navcontent %}
  <ul class="pam">
    <li class="pam inbl"><a href="{% url 'lead:index' %}" title="">Mes contacts</a></li>
    <li class="pam inbl"><a href="#" title="">Action #2</a></li>
  </ul>
{% endblock navcontent %}

{% block maincontent %}
  <div class="flex-container--column">
    <div class="item-center"><strong>Nom d'utilisateur</strong> : <em>{{user}}</em></div>
    <div class="item-center"><strong>Date d'inscription</strong> : <em>{{date_joined}}</em></div>
    <div class="item-center"><strong>Dernière connection</strong> : <em>{{last_login}}</em></div>
  </div>
{% endblock maincontent %}