a14n/urls.py
from django.urls import include, path

from a14n import views as a14n_views

urlpatterns = [
    path('signup/', a14n_views.signup, name='signup'),
    path('', include('django.contrib.auth.urls')),
]

core/urls.py
# from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView as tw

from core import views as core_views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', tw.as_view(template_name='home.html'), name='home'),
    path('about/', tw.as_view(template_name="about.html"), name='about'),
    path('hopla', core_views.hopla, name='hopla'),
    path('my/', include('a14n.urls')),
    path('user/', include('user.urls')),
    path('lead/', include('lead.urls')),
]

user/urls.py
from user.views import UserDetail, UserUpdate

from django.urls import path


app_name = 'user'
urlpatterns = [
    path('', UserDetail.as_view(), name='detail'),
    path('edit', UserUpdate.as_view(), name='update'),
]

core/views.py
from django.http import HttpResponse
from django.shortcuts import render


def hopla(request):
    return HttpResponse("Hopla, Seppi bring a Wurschtsalat avec un amer!")

core/templates/about.html
{% extends 'base.html' %}

{% block title %}Mentions légales{% endblock %}

{% block headercontent %}
    <h2>WTF - mentions légales</h2>
{% endblock headercontent %}

{% block maincontent %}
    <div>
      <h4>Contexte <em>pédagogique</em></h4>
      <p>
        Le présent service est le travail d'étude issu du 13ème projet du <a href="https://openclassrooms.com/fr/paths/68-developpeur-dapplication-python" title="Open Classrooms - Développeur d'application Python">pacours développeur d'application Python</a> proposé par <a href="https://openclassrooms.com" title="Site d'OpenClassrooms">OpenClassrooms</a>. Il s'agit de développer un projet <em>libre</em> avec une <em>portée sociale</em>.
      </p>

      <blockquote>
        <p>
          Menez un projet numérique de la forme qui vous semblera la plus adaptée pour répondre à un besoin autour de vous. Il peut s’agir d’un site de réservation pour l’association de théâtre de votre ville, d’une application pour localiser et référencer les objets trouvés pendant un festival, etc. Prenez le temps de choisir un sujet qui vous touche et pour lequel vous ressentez un véritable besoin.
        </p>
      </blockquote>

      <p>Les outils ci-dessous font partit du périmètre pédagogique :</p>

      <ul class="pas">
        <li class="pas inbl mas"><a href="https://www.djangoproject.com">Django</a></li>
        <li class="pas inbl mas"><a href="https://www.git-scm.com">git</a></li>
        <li class="pas inbl mas"><a href="https://www.github.com">GitHub</a></li>
        <li class="pas inbl mas"><a href="https://www.postgresql.org">PostgreSQL</a></li>
        <li class="pas inbl mas"><a href="https://www.heroku.com">Heroku</a></li>
        <li class="pas inbl mas"><a href="https://travis-ci.org/freezed/ocp13/builds"></a>Travis CI</li>
        <li class="pas inbl mas"><a href="https://coveralls.io/github/freezed/ocp13"></a>Coveralls</li>
        <li class="pas inbl mas"><a href="https://sentry.io/team-rocket/ocp13/"></a>Sentry</li>
        <li class="pas inbl mas"><a href="https://fr.wikipedia.org/wiki/Cerveau">le cerveau</a> (un peu)</li>
      </ul>

      <h4>Contexte <em>utilisateur</em></h4>
      <p>
        <a href="https://refuge.la-cordee.net/users/3271">Valérie</a> et <a href="https://refuge.la-cordee.net/users/2579">Serge</a> sont travailleurs indépendants. Nous nous <a href="https://refuge.la-cordee.net/messages/5733">rencontrons</a> à <em>Lyon</em> dans la <a href="https://www.la-cordee.net/">communauté de travail</a> que nous fréquentons. Pour leurs activités respectives ils sont à la recherche d'un outil qui leur permettrait de gérer aisément leur <em>réseau de contacts</em> : prospection, suivi, opportunités etc.
      </p>
      <p>
        Bien qu'aillant chacun des activités (<em>très</em>) différentes, après une écoute de leurs problématiques respectives, un certain nombre de leurs besoins sont similaires et sont compatibles avec un outil commun. En plus il pourrait même convenir à d'autres indépendants de cette <em>communauté de travail</em> ou d'une autre
      </p>

      <p>
        L'intégralité du code source est disponible sur <a href="https://github.com/freezed/ocp13" title="Source du service sur GitHub">GitHub</a>.
      </p>
    </div>

    <hr />

    <div class="pas">
      <h3>Données personnelles</h3>
      <p><em>Ça vient, ça vient…</em></p>
    </div>

    <hr />

    <div>
      <h3>Mentions légales</h3>
      <h5>À qui j'ai piqué des trucs ?</h5>

      <ul class="pas">
        <li class="pas inbl mas">Template HTML5 & <em>Elsass Lipsum</em> fourni par <a href="https://schnaps.it/" title="Générateur de template HTML5 since 1664">Schnaps.it</a></li>
        <li class="pas inbl mas"><em>Favicon</em> : <a href="https://origin.fontawesome.com/icons/connectdevelop?style=brands" title="The web's most popular icon set and toolkit">Font Awesome - connectdevelop</a></li>
        <li class="pas inbl mas">Harmonie de couleurs : <a href="https://coolors.co/" title="The super fast color schemes generator!">coolors.co</a></li>
        <li class="pas inbl mas">La présente page est très fortement inspirée de <a href="https://www.alsacreations.com/page/about/">celle d'Alsacréation</a>, merci vielmol.</li>
      </ul>
    </div>

    <hr />

    <div>
      <h3>Hébergement</h3>
      <div class="txtcenter">
        <p>
          <a href="https://www.heroku.com/about">
            <img src="https://brand.heroku.com/static/media/heroku-logo-stroke.aa0b53be.svg" alt="heroku.com" height="20" />
          </a>
        </p>
        <p>
          <a href="https://www.heroku.com/about">Heroku</a>
        </p>
      </div>
    </div>

    <hr />

    <div>
      <h3>Contenus et outils</h3>
      <p>
          Ce service est distribué dans l'espoir qu'il sera utile, mais sans aucune garantie; sans même la garantie implicite de qualité marchande ou d'adéquation à un objet particulier. L'administrateur ne peut en aucun cas être tenu pour responsable de tous dommages quels qu'ils soient, y compris mais non de façon limitative, des dommages directs, indirects, accessoires ou incidents, des pertes de bénéfices ou de l'interruption d'activité, résultant de l'utilisation ou de l'impossibilité d'utilisation de ce service.
      </p>

      <p>
          Tu as lu jusqu'ici? Bravo! Tu gagnes une bière avec le mot de passe suivant la prochaine fois que tu me croises : <em>Cœur d'artichaud à la moutarde à l'ancienne</em>. Merci, tu peux reprendre une vie normale.
      </p>
    </div>
{% endblock maincontent %}

core/templates/base.html
<!doctype html>
<html class="no-js" lang="fr">

  <head>
    <meta charset="UTF-8">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

    <title>{% block title %}?{% endblock %} - [ ocp13 ]</title>

    {% load static %}
    <link href="{% static 'img/favico.png' %}" media='all' type="image/png" rel="shortcut icon">
    <link href="{% static 'css/knacss.css' %}" media='all' type='text/css' rel='stylesheet'>
    <link href="{% static 'css/styles.css' %}" media='all' type='text/css' rel='stylesheet'>

  </head>

  <body>

    <header id="header" role="banner" class="pam">
      <h1>ocp13</h1>
      {% block headercontent %}{% endblock headercontent %}
    </header>

    <div class="flex-container">

      <aside class="mod w20 pam aside">

        <nav id="navigation" role="navigation">
          <ul class="pam">
            <li class="pam inbl"><a href="{% url 'home' %}" title="Accueil">Accueil</a></li>
    {% if user.is_authenticated %}
            <li class="pam inbl"><a href="{% url 'user:detail' %}" title="Lien vers mon compte'">Mon compte</a></li>
      {% block navcontent %}{% endblock navcontent %}
            <li class="pam inbl"><a href="{% url 'logout' %}?next={{request.path}}" title="Lien vers la page de déconnection">Me déconnecter</a></li>
    {% else %}
            {% include 'a14n/anonymous.html' %}
    {% endif %}
          </ul>
        </nav>
      </aside>

      <main id="main" role="main" class="flex-item-fluid pam">
    {% block maincontent %}
        <p>Yoo ch'ai lu dans les DNA que le Racing a encore perdu contre Oberschaeffolsheim. Verdammi et moi ch'avais donc parié deux knacks et une flammekueche. Ah so ? T'inquiète, ch'ai ramené du schpeck, du chambon, un kuglopf et du schnaps dans mon rucksack. Allez, s'guelt ! Wotch a kofee avec ton bibalaekaess et ta wurscht ? Yeuh non che suis au réchime, je ne mange plus que des Grumbeere light et che fais de la chym avec Chulien. Tiens, un rottznoz sur le comptoir. gewurztraminer turpis, suspendisse commodo Oberschaeffolsheim ornare aliquam semper Miss Dahlias Mauris turpis sagittis kuglopf eleifend dignissim baeckeoffe geht's Richard Schirmeck mollis habitant schnaps ante et sit leo schpeck sit Salu bissame Salut bisamme varius quam.</p>
        <p>Tu restes pour le lotto-owe ce soir, y'a baeckeoffe ? Yeuh non, merci vielmols mais che dois partir à la Coopé de Truchtersheim acheter des mänele et des rossbolla pour les gamins. Hopla tchao bissame ! Consectetur adipiscing elit amet elementum nullam bissame bredele Heineken picon bière gal sed risus, condimentum Verdammi ch'ai ac réchime météor barapli s'guelt quam, non Christkindelsmärik blottkopf, Carola tellus rucksack vielmols, Gal !</p>
    {% endblock maincontent %}
      </main>
    </div>

    <footer id="footer" role="contentinfo" class="pam">
    {% block footercontent %}
      <div class="grid-7-small-2 has-gutter">
        <div class="grid-offset"></div>
        <div class="grid-offset"></div>
        <div class="txtcenter"><a href="{% url 'about' %}" title="À propos">À propos</a></div>
        <div class="txtcenter"><a href="https://schnaps.it/" title="Générateur de template HTML5 since 1664">schnaps.it</a></div>
        <div class="txtcenter"><a href="https://github.com/freezed/ocp13" title="Source">Sources</a></div>
      </div>
    {% endblock footercontent %}
    </footer>

  </body>
</html>

core/templates/home.html
{% extends 'base.html' %}

{% block title %}Hopla{% endblock %}

{% block navcontent %}
        <p>Lorem Salu bissame ! Wie geht's les samis ? Hans apporte moi une Wurschtsalad avec un picon bitte, s'il te plaît. Voss ? Une Carola et du Melfor ? Yo dû, espèce de Knäckes, ch'ai dit un picon !</p>
{% endblock navcontent %}